""" *******************************************************************************************************************
|
|  Name        :  _params.py
|  Description :  Params
|  Project     :  risksense_api
|  Copyright   :  2019 RiskSense, Inc.
|  License     :  Apache-2.0 (https://www.apache.org/licenses/LICENSE-2.0.txt)
|
******************************************************************************************************************* """


class Projection:

    """ Projection class and params"""

    BASIC = "basic"
    DETAIL = "detail"


class SortDirection:

    """ SortDirection class and params"""

    ASC = "ASC"
    DESC = "DESC"


class SortField:

    """ SortField class and params"""

    ACTUAL_RESULT = "actual_result"
    APP_COUNT_TOTAL = "app_count_total"
    APP_CRITICAL_TOTAL = "app_critical_total"
    APP_FINDING_TOTAL = "app_finding_total"
    APP_HIGH_TOTAL = "app_high_total"
    APP_INFO_TOTAL = "app_info_total"
    APP_LOW_TOTAL = "app_low_total"
    APP_MEDIUM_TOTAL = "app_medium_total"
    APP_COUNT = "appCount"
    APP_ID = "application.id"
    APP_NAME = "application.name"
    APP_FINDING_COUNT = "applicationFindingCount"
    ARCH_LIST = "architectureList"
    ASSESSMENT_LABELS = "assessment_labels"
    ASSET_OWNER = "asset_owner"
    ASSET_TAGS = "asset_tags"
    ASSET_TOTAL = "asset_total"
    ASSIGNED_USERS = "ASSIGNED_USERS"
    ASSIGNMENTS = "assignments"
    CIA_IMPACT_LIST = "ciaImpactList"
    CMDB_ASSET_CRITICALITY = "cmdb_asset_criticality"
    CMDB_ASSET_TAG = "cmdb_asset_tag"
    CMDB_CUST_FIELD_1 = "cmdb_custom_field_1"
    CMDB_CUST_FIELD_2 = "cmdb_custom_field_2"
    CMDB_CUST_FIELD_3 = "cmdb_custom_field_3"
    CMDB_CUST_FIELD_4 = "cmdb_custom_field_4"
    CMDB_CUST_FIELD_5 = "cmdb_custom_field_5"
    CMDB_CUST_FIELD_6 = "cmdb_custom_field_6"
    CMDB_CUST_FIELD_7 = "cmdb_custom_field_7"
    CMDB_CUST_FIELD_8 = "cmdb_custom_field_8"
    CMDB_CUST_FIELD_9 = "cmdb_custom_field_9"
    CMDB_CUST_FIELD_10 = "cmdb_custom_field_10"
    CMDB_FERPA_COMPL_ASSET = "cmdb_ferpa_compliance_asset"
    CMDB_HIPAA_COMPL_ASSET = "cmdb_hipaa_compliance_asset"
    CMDB_LAST_SCAN_DATE = "cmdb_last_scan_date"
    CMDB_LOCATION = "cmdb_location"
    CMDB_MANAGED_BY = "cmdb_managed_by"
    CMDB_MANUFACTURED_BY = "cmdb_manufactured_by"
    CMDB_MODEL = "cmdb_model"
    CMDB_OS = "cmdb_operating_system"
    CMDB_OWNED_BY = "cmdb_owned_by"
    CMDB_PCI_COMPL_ASSET = "cmdb_pci_compliance_asset"
    CMDB_SUPPORT_GROUP = "cmdb_support_group"
    CMDB_SUPPORTED_BY = "cmdb_supported_by"
    CMDB_SYNC_STATUS = "cmdb_sync_status"
    CMDB_UNIQUE_ID = "cmdb_unique_id"
    COMPILER_LIST = "compilerList"
    CONNECTOR_COUNT = "connectorCount"
    CREATED = "created"
    CRITICALITY = "criticality"
    CRITICALITY_STATE = "criticality_state"
    CVE_PUBLISH_DATES = "cve_publish_dates"
    CVES = "cves"
    CVSS2_BASE_AC = "cvss2BaseAC"
    CVSS2_BASE_AI = "cvss2BaseAI"
    CVSS2_BASE_AU = "cvss2BaseAu"
    CVSS2_BASE_AV = "cvss2BaseAV"
    CVSS2_BASE_CI = "cvss2BaseCI"
    CVSS2_BASE_II = "cvss2BaseII"
    CVSS2_BASE_SCORE = "cvss2BaseScore"
    CVSS3_BASE_A = "cvss3BaseA"
    CVSS3_BASE_AC = "cvss3BaseAC"
    CVSS3_BASE_AV = "cvss3BaseAV"
    CVSS3_BASE_C = "cvss3BaseC"
    CVSS3_BASE_I = "cvss3BaseI"
    CVSS3_BASE_PR = "cvss3BasePR"
    CVSS3_BASE_S = "cvss3BaseS"
    CVSS3_BASE_SCORE = "cvss3BaseScore"
    CVSS3_BASE_UI = "cvss3BaseUI"
    CWE_HASH = "cwe_hash"
    CWES = "cwes"
    DAYS_REMAINING = "daysRemaining"
    DB_COUNT = "dbCount"
    DESC = "DESCRIPTION"
    DISCOVERED_DATES = "discovered_dates"
    DISCOVERED_ON = "discovered_on"
    DUE_DATES = "due_dates"
    DUE_DATE = "dueDate"
    EASILY_EXPLOITABLE = "easily_exploitable"
    EXPECTED_RESULT = "expected_result"
    EXPLOIT_CATEGORIES = "exploit_categories"
    EXPLOIT_LEVEL_LIST = "exploitLevelList"
    EXPLOITS = "exploits"
    FINDINGS_DIST_CRITICAL = "findingsDistribution.critical"
    FINDINGS_DIST_HIGH = "findingsDistribution.high"
    FINDINGS_DIST_INFO = "findingsDistribution.info"
    FINDINGS_DIST_LOW = "findingsDistribution.low"
    FINDINGS_DIST_MEDIUM = "findingsDistribution.medium"
    FINDINGS_DIST_TOTAL = "findingsDistribution.total"
    FINDINGTYPE = "findingType"
    FINDING_TYPE = "finding_type"
    FOUND_BY_ID = "found_by_id"
    FOUND_BY_IDS = "found_by_ids"
    FUNCTION_PROTOTYPE_LIST = "functionProtoypeList"
    FUNCTION_REL_LOC_LIST = "functionRelativeLocationList"
    GENERIC_STATE = "generic_state"
    GROUP_IDS = "group_ids"
    GROUP_NAMES = "group_names"
    HAS_CLOSED_RANSOMWARE_FINDING = "has_closed_ransomware_finding"
    HAS_CONNECTOR_TICKET = "HAS_CONNECTOR_TICKET"
    HAS_CVE_PUBLISH_DATES = "has_cve_publish_dates"
    HAS_CVES = "has_cves"
    HAS_CWE = "has_cwe"
    HAS_DEFAULT_CREDS = "has_default_credentials"
    HAS_EXPLOIT = "has_exploit"
    HAS_MALWARE = "has_malware"
    HAS_MANUAL_EXPLOIT = "has_manual_exploit"
    HAS_NOTE = "has_note"
    HAS_OPEN_EXPLOIT = "has_open_exploit"
    HAS_OPEN_MALWARE = "has_open_malware"
    HAS_OPEN_MANUAL_EXPLOIT = "has_open_manual_exploit"
    HAS_OPEN_PE_RCE = "has_open_pe_rce"
    HAS_OPEN_RANSOMWARE_FINDING = "has_open_ransomware_finding"
    HAS_OPEN_RANSOMWARE_FINDING_W_RCE_PE = "has_open_ransomware_finding_with_rce_pe"
    HAS_OPEN_THREAT = "has_open_threat"
    HAS_OPEN_WEAPONIZATION = "has_open_weaponization"
    HAS_OWASP = "has_owasp"
    HAS_OWASP_A6 = "has_owasp_a6"
    HAS_PATCH = "has_patch"
    HAS_PE = "has_pe"
    HAS_PE_RCE = "has_pe_rce"
    HAS_RANSOMWARE_WITH_PE_RCE = "has_ransomware_with_pe_rce"
    HAS_RCE = "has_rce"
    HAS_SANS = "has_sans"
    HAS_SQL_INJECTION = "has_sql_injection"
    HAS_THREAT = "has_threat"
    HAS_TICKET = "has_ticket"
    HAS_TOP_25_CWE = "has_top_25_cwe"
    HAS_VULNS = "has_vulnerabilities"
    HAS_XSS = "has_xss"
    HIGH_THREAT = "high_threat"
    HOST_COUNT_TOTAL = "host_count_total"
    HOST_CRITICAL_TOTAL = "host_critical_total"
    HOST_FINDING_TOTAL = "host_finding_total"
    HOST_HIGH_TOTAL = "host_high_total"
    HOST_INFO_TOTAL = "host_info_total"
    HOST_LOW_TOTAL = "host_low_total"
    HOST_MEDIUM_TOTAL = "host_medium_total"
    HOST_COUNT = "hostCount"
    HOST_FINDING_COUNT = "hostFindingCount"
    HOST_ID = "hostId"
    HOSTNAME = "hostName"
    HOSTNAME_NOT_DETECTED = "hostname_not_detected"
    ID = "id"
    IP_ADDRESS_TYPE = "ip_address_type"
    IP_ADDRESS = "ipAddress"
    IS_COMPLETE = "is_complete"
    KINGDOM = "kingdom"
    LAST_FOUND_ON = "last_found_on"
    LASTFOUNDON = "lastFoundOn"
    LAST_SCAN_TIME = "lastScanTime"
    LICENSE_FAMILY = "licenseFamily"
    LINE_LIST = "lineList"
    LOCKED_LOWER = "locked"
    LOCKED_UPPER = "LOCKED"
    MALWARE = "malware"
    MALWARE_CATEGORIES = "malware_categories"
    MANUAL_EXPLOITS = "manual_exploits"
    MANUAL_FINDING_REPORT_TYPES = "manual_finding_report_types"
    MANUAL_FINDING_REPORTS = "manual_finding_reports"
    METRIC_EXCLUDE = "metric_exclude"
    METRIC_EXCLUDE_REASON = "metric_exclude_reason"
    MODULE_NAMES = "moduleNames"
    NAME = "name"
    NETBIOS = "netbios"
    NETWORK_NAME = "network.name"
    NETWORK_PARTITION_NAMES = "network_partition_names"
    NETWORK_PARTITION_TYPE = "network_partition_type"
    NETWORK_PARTITION_TYPES = "network_partition_types"
    NEWLY_CREATED_HOST = "newly_created_host"
    NEWLY_CREATED_WEBAPP = "newly_created_webapp"
    OLDEST_OPEN_FINDING_W_THREAT_DISC_ON = "oldestOpenFindingWithThreatDiscoveredOn"
    OPEN_CVES = "open_cves"
    OPEN_EXPLOIT_CATEGORIES = "open_exploit_categories"
    OPEN_MALWARE = "open_malware"
    OPEN_MALWARE_CATEGORIES = "open_malware_categories"
    OPEN_RANSOMWARE_CVES = "open_ransomware_cves"
    OPEN_RANSOMWARE_FAMILIES = "open_ransomware_families"
    OPEN_RANSOMWARE_TRENDING_DATE = "open_ransomware_trending_date"
    OPEN_THREAT_CATEGORIES = "open_threat_categories"
    OPEN_THREAT_LAST_TRENDING_ON = "open_threatLastTrendingOn"
    OPEN_FINDING_COUNT = "openFindingCount"
    OPEN_VULN_LAST_TRENDING_ON = "openVulnLastTrendingOn"
    OS_CLASS = "operatingSystem.class"
    OS_FAMILY = "operatingSystem.family"
    OS_NAME = "operatingSystem.name"
    OS_VENDOR = "operatingSystem.vendor"
    OS_LIST = "osList"
    OUTPUT = "output"
    OWASPS = "owasps"
    OWNER = "OWNER"
    PARENT_ID = "parent_id"
    PAST_DUE = "past_due"
    PATCH_FAMILIES = "patch_families"
    PATCH_TITLE = "patch_title"
    PATCH_VENDORS = "patch_vendors"
    PCI = "PCI"
    PCI_RELATED_LIST = "pciRelatedList"
    PERCENTAGE_COMPLETE = "percentageComplete"
    PORT = "port"
    PORT_NUMBERS = "port_numbers"
    PRIORITY = "priority"
    RANSOMWARE_DISC_DATES = "ransomware_discovered_dates"
    RANSOMWARE_FAMILIES = "ransomware_families"
    RANSOMWARE_TRENDING_DATE = "ransomware_trending_date"
    READ_ONLY = "READ_ONLY"
    REMEDIATION_EFFORT_LIST = "remediationEffortList"
    REMEDIATION_TIME = "remediationTime"
    REQUEST_METHOD = "request_method"
    RESOLVED_ON = "resolved_on"
    RISK_RATING = "riskRating"
    RISK_TYPE = "riskType"
    RS3 = "rs3"
    SCANNER_NAME = "scanner_name"
    SCANNER_NAMES = "scanner_names"
    SCANNER_PLUGIN_STATUS = "scanner_plugin_status"
    SCANNER_VERSION_LIST = "scannerVersionList"
    SCHEDULE_EARNED_VALUE = "SCHEDULE_EARNED_VALUE"
    SCHEDULE_PERFORMANCE_INDEX = "SCHEDULE_PERFORMANCE_INDEX"
    SCHEDULE_PLANNED_VALUE = "SCHEDULE_PLANNED_VALUE"
    SCHEDULE_VARIANCE = "SCHEDULE_VARIANCE"
    SCOPE_LIST = "scopeList"
    SERVICE_NAMES = "service_names"
    SEVERITIES = "severities"
    SEVERITY = "severity"
    SEVERITY_GROUP = "severity_group"
    SEVERITY_UPDATE_STATE = "severity_update_state"
    SOURCE = "source"
    SOURCE_PATCH_IDS = "source_patch_ids"
    SOURCE_ORIGIN_LIST = "sourceOriginList"
    SOURCES = "sources"
    START_DATE = "startDate"
    STATE = "state"
    SYSTEM_LOCKED = "SYSTEM_LOCKED"
    TAG_CONNECTOR_ID = "TAG_CONNECTOR_ID"
    TAG_CONNECTOR_NAME = "TAG_CONNECTOR_NAME"
    TAGS = "tags"
    TECHNOLOGY = "technology"
    TEST_STATUS = "test_status"
    THREAT_CATEGORIES = "threat_categories"
    THREAT_LAST_TRENDING_ON = "threatLastTrendingOn"
    THREATS = "threats"
    TICKET_ID = "TICKET_ID"
    TICKET_STATUS = "TICKET_STATUS"
    TITLES = "titles"
    TOTAL_FINDING_COUNT = "totalFindingCount"
    TYPE = "type"
    UNIQUE_ID = "unique_id"
    UPDATED = "updated"
    URL = "url"
    VISIBILITY_LIST = "visibilityList"
    VULN_LAST_TRENDING_ON = "vulnLastTrendingOn"
    WEB_APP_ID = "web_app_id"
    WEB_APP_DESC = "webapp_description"
    XRS3 = "xrs3"
    XRS3_DATE = "xrs3_date"
    XRS3_IMPACT = "xrs3Impact"
    XRS3_IMPACT_ON_CATEGORY = "xrs3ImpactOnCategory"


class ScheduleFreq:
    DAILY = "DAILY"
    WEEKLY = "WEEKLY"
    MONTHLY = "MONTHLY"


"""
   Copyright 2019 RiskSense, Inc.

   Licensed under the Apache License, Version 2.0 (the "License");
   you may not use this file except in compliance with the License.
   You may obtain a copy of the License at:

   http://www.apache.org/licenses/LICENSE-2.0

   Unless required by applicable law or agreed to in writing, software
   distributed under the License is distributed on an "AS IS" BASIS,
   WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
   See the License for the specific language governing permissions and
   limitations under the License.
"""
